name: "Validate Generated Files"
description: "Validate Generated Files00"

inputs:
  to:
    description: "The person or thing to say hello to"
    required: true

runs:
  using: "composite"
  steps:
    - name: Say hello
      shell: bash
      run: echo "Hello ${{ inputs.to }}"
