name: "Generate Files"
description: "Generate Files"

inputs:
  config-file-name:
    description: ""
    required: true
    default: "configVariables.yml"
  location-config-files:
    description: ""
    required: true
    default: "config"
  output-location:
    description: ""
    required: true
    default: "generated"

runs:
  using: "composite"
  steps:
    - name: Join config files
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/joinConfig.sh
        $GITHUB_ACTION_PATH/joinConfig.sh ${{ inputs.location-config-files }} ${{ inputs.output-location }} ${{ inputs.config-file-name }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.0
    - name: Install pip requirements
      shell: bash
      run: pip3 install -r $GITHUB_ACTION_PATH/requirements.txt
    - name: Generate files
      shell: bash
      run: python3 $GITHUB_ACTION_PATH/generateFiles.py $GITHUB_ACTION_PATH ${{ inputs.output-location }} ${{ inputs.config-file-name }}
