#!/bin/bash

LOCATION_CONFIG_FILES=$1;
OUTPUT_LOCATION=$2;
CONFIG_FILENAME=$3;

rm -f $OUTPUT_LOCATION/$CONFIG_FILENAME
touch $OUTPUT_LOCATION/$CONFIG_FILENAME
echo "---" >> $OUTPUT_LOCATION/$CONFIG_FILENAME

for configFile in $LOCATION_CONFIG_FILES/*.yml;
do
  echo "Processing $f file...";
  cat $configFile >> $OUTPUT_LOCATION/$CONFIG_FILENAME
done